### ISSUE TITLE
Move 1.4 support

### ISSUE THREAD

**Issue by villesundell** [pontem-network/move-tools#151]
Hello everyone!
When Move 1.4 (https://github.com/diem/diem/releases/tag/diem-core-v1.4.1) would be supported?
I would need `phantom` support :laughing: (Specifically, I would need support for different abilities for phantom types than the struct itself. In my understanding this is not supported in "vanilla" Move, although older Move conceptually supports phantom types.)

Move 1.4 changelog is a bit misleading, since `phantom` is not listed in `changes/` on that tag, but is still implemented, as can be seen [here](https://github.com/diem/diem/blob/416fdd3b18d02b2a099917467910d5a6865f2fed/language/diem-framework/modules/Diem.move).

**Comment by RIg410** [comment]
Greetings.
We missed version 1.4 and are currently working on 1.5.
1.5 Coming soon)

**Comment by villesundell** [comment]
Great! It seems that the WIP branch `v1.5-build` is building my project fine, so I can continue development :slightly_smiling_face:  Thank you guys once again :heart:

**Comment by villesundell** [comment]
Move 1.5 support has landed, closing this :slightly_smiling_face:
