### ISSUE TITLE
Dove "run" doesn't handle multiple script in the same file

### ISSUE THREAD

**Issue by villesundell** [pontem-network/move-tools#98]
`dove run` does not handle script files with multiple `script{}`s correctly.

## Example
Consider the following example:
```move
// dummy.move:
script {
    fun main() {
        assert(true, 0);
    }
}

script {
    fun main() {
        assert(true, 0);
    }
}
```

And try to run it with: `dove run --file dummy`

## Expected result
`script{}`s should be run one-by-one, in the specified order.

## Actual result
```
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', library/alloc/src/vec/mod.rs:1355:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by borispovod** [comment]
Thank you for bug report @villesundell, we are working on it.

**Comment by fzzr-** [comment]
#100 fixes this issue. Thanks!
